config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  root 'users#dashboard'    
  get '/static/index' => 'static#index'
  post '/transfers/create' => 'transfers#create'
  resources :accounts, only: [:edit, :update]
  resources :transfers, only: [:edit, :update, :new]

end

app/models/user.rb
class User < ActiveRecord::Base
	has_one :account, :dependent => :destroy
	has_many :transfers, through: :accounts
  has_many :transactions, through: :accounts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable
  # validates :fname, :lname, presence: true
  validates :email, presence: true, uniqueness: true

  #validetes :uid, uniqueness: true

  after_create :create_account

  def self.from_omniauth(auth)
    user = User.where(auth.slice(:uid)).first_or_create do |user|
      user.uid = auth.uid
      user.fname = auth.info.first_name
      user.email = auth.info.email
      user.lname = auth.info.last_name
      user.profile_pic = auth.extra.raw_info.profile_picture_url
      user.token = auth.credentials.token     
    end
  end

  def self.new_with_session(params, session)
	  if session["devise.user_attributes"]
	    new(session["devise.user_attributes"], without_protection: true) do |user|
	      user.attributes = params
	    end
	  else
	    super
	  end    
	end

   def self.all_except(user)
  where.not(id: user)
  end

  protected

  def create_account
    Account.create!(:user_id => self.id, :balance => 500, :remaining_borrow => 0, lending_funds: 0)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :auth_user, except: [:new]

	def new 
	end

	def create
	end

	def edit
	end

	def update
	end

	def show
	end

	def delete
	end

	def dashboard
		@account = current_user.account
		@user = current_user

		if current_user.account.transfers
		@transfers = current_user.account.transfers.where(completed: false)
		end
		if current_user.account.collateral
		@collateral = current_user.account.collateral*0.9
		@remaining = current_user.account.remaining_borrow
		end
	end
end


app/views/users/_body_DB.html.erb
<!-- <div class="container container_border">
  Add back <div class="col-md-8"> to top and bottom
    -->
    <!-- New rows may have messed up modals for "edit" links -->
    <!-- FIRST ROW -->
    <div class="col-md-4 slight_margin">
      <div class="row profile dashboard_divs">
        <div class="row custom_rows">
          <div class="selfie"></div>
        </div>
        <div class="row custom_rows" >
          <div class = "col-md-12">
            <h2  class = "my_account"><%= @user.fname + " " + @user.lname %></h2>
          </div>
          <div class="row custom_rows">
            <div class="horiz_line"></div>
          </div>
        </div>
        <!-- Remaining Borrow Row -->
        <div class="row custom_rows">
          <div class = "col-md-8">
            <h4 >Available Borrow Amount: </h4>
          </div>
        </div>
        <div class="row custom_rows">
          <div class="col-md-4">
            <p> $<%= current_user.account.remaining_borrow.round(2)%> </p>
          </div>
        </div>
        <div class="row custom_rows">
          <div class="separation_line"></div>
        </div>
        <!-- Collateral Row -->
        <div class="row custom_rows">
          <div class="col-md-5">
            <h4> Current collatoral:</h4>
          </div>
        </div>
        <div class="row custom_rows">
          <div class="col-md-2">
            <p> $<%= @collateral%> </p>
          </div>
          <div class="col-md-2">
            <!-- Large modal -->
            <a href="collateralModal" data-toggle="modal" data-target=".collateral">Edit</a>
            <!-- <button class="btn btn-primary btn-sm" data-toggle="modal" data-target=".collateral">Edit</button> -->
            <div id="collateralModal" class="modal fade collateral" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-lg">
                <div class="modal-content">
                  <%= form_for(@account, method: 'put') do |f| %>
                  <div class="modal-body">
                    <!-- Set Collateral Form -->
                    <div id="collateral_form">
                      <h4>Set Desired Collateral:</h4>
                      <%= "Your balance is: #{current_user.account.balance}" %>
                      <div class="form-group">
                        <%= f.number_field :collateral, placeholder: "Collateral" %>
                      </div>
                      <div class="form-group">
                        <%= f.submit "Submit", :class => "toggle_forms_button" %>
                      </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row custom_rows">
          <div class="separation_line"></div>
        </div>
        <!-- Lending Funds Row -->
        <div class="row custom_rows">
          <div class="col-md-5">
            <h4>Current lending funds:</h4>
          </div>
        </div>
        <div class="row custom_rows">
          <div class="col-md-2">
            <p> $<%= current_user.account.lending_funds.round(2)%> </p>
          </div>
          <div class="col-md-2">
            <!-- Loan modal -->
            <!--           <button class="btn btn-primary btn-sm" data-toggle="modal" data-target=".loan">Edit</button> -->
            <a href="lendingModal" data-toggle="modal" data-target=".collateral">Edit</a>
            <div id="lendingModal" class="modal fade loan" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-lg">
                <div class="modal-content">
                  <%= form_for(@account, method: 'put') do |f| %>
                  <div class="modal-body">
                    <!-- Set Collateral Form -->
                    <div id="collateral_form">
                      <h4>Set Desired Lending Funds:</h4>
                      <%= "Your balance is: #{current_user.account.balance}" %>
                      <div class="form-group">
                        <%= f.number_field :lending_funds, placeholder: "lending_funds" %>
                      </div>
                      <div class="form-group">
                        <%= f.submit "Submit", :class => "toggle_forms_button" %>
                      </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <%=button_to "Borrow!", '/transfers/new', :class => "borrow_button", :method => :get%>
      </div>
    </div>
    <!-- Credit Score Standing -->
    <div class="col-md-8">
      <div class="row custom_rows">
        <div class="credit_score col-md-12 dashboard_divs">
          <h3>Credit Standing:</h1>
          <h2>GREAT!</h2>
        </div>
      </div>
      <!-- Payments Div -->
      <div class="row track_progress_div dashboard_divs">
        <h2 class = "track">You have paid:</h2>
        <div class="progress">
          <% if current_user.account.collateral %>
          <% percent = (((current_user.account.remaining_borrow)/@collateral)*100).round(0) %>
          <% else %>
          <% percent = 100 %>
          <% end %>
          <div class="progress-bar custom_progress" role="progressbar" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100" style="width: <%= percent %>%;">
            <%= percent %>%
          </div>
        </div>
      </div>
      <div class="row borrowing_table dashboard_divs">
        
        <h2>You are borrowing:</h2>
        <% if @transfers %>
        <table class="table table-striped table-bordered" border = "3">
          <tr>
            <th>Date Created</th>
            <th>Message</th>
            <th>Amount</th>
            <th>Due date</th>
            <th></th>
          </tr>
          <% @transfers.each do |transfer| %>
          <tr>
            <td><%= transfer.created_at.strftime("%m/%d/%Y") %></td>
            <td><%=transfer.message.upcase%></td>
            <td>$<%=transfer.amount%></td>
            <td><%=transfer.expiration_date.strftime("%m/%d/%Y")%></td>
            <td><%=link_to "Make Payment", edit_transfer_path( transfer), :method => :get %></td>
          </tr>
          <% end %>
        </table>
        <% end %>
      </div>
    </div>

app/views/users/_header_DB.html.erb
<!-- <nav class="navbar navbar-default" role="navigation">
 -->  <!--   <div class="container-fluid">
    -->    <div class="row header_row">
      <div class="collapse navbar-collapse">
        <div class ="dash_brand">| Seed |
          <img class="small_logo" src="/assets/logo2Seed.png" alt="Logo">
        </div>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <img src=<%=current_user.profile_pic%> class="nav-thumbnail">
          </li>
          <li class="dropdown">
            <a id="drop1" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown"><%= @user.fname %> <b class="caret"></b></a>
            <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
              <li role="presentation"><a role="menuitem" tabindex="-1" href="http://twitter.com/fat">User Settings</a></li>
              <li role="presentation"><a role="menuitem" tabindex="-1" href="http://twitter.com/fat">Account Settings</a></li>
              <li role="presentation"><%=link_to('Logout', destroy_user_session_path, :method => :delete)%></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
<!--   </div>
-->
<script type="text/javascript">
$('.dropdown-toggle').dropdown();
</script>

app/views/users/dashboard.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>Seed | Social Lending</title>
	</head>
	<body style="background-color: #c8cdcf;">
		<%= render "header_DB" %>
		<%= render "body_DB" %>

		<script type="text/javascript">
		$(window).load(function(){
		$('#autoModal').modal('show');
		});
		</script>


		<!-- Set Collateral/Lending Funds Modal -->
		<% if @account.collateral.nil?  %>
		<div class="modal fade" id="autoModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
						<h4 class="modal-title" id="myModalLabel">Account Setup</h4>
					</div>
					<%= form_for(@account, method: 'put') do |f| %>
					<div class="modal-body">
						<!-- Set Collateral Form -->
						<div id="collateral_form">
							<h4>Set Desired Collateral:</h4>
							<p> Your collateral will serve as a cushion to guarantee that you will always have the funds to pay back your loans in full. You can borrow up to 90% of your collateral at any time, ensuring that you can pay back both the original amount you borrowed and the added interest on the loan. </p>
							<%= "Your balance is: #{current_user.account.balance}" %>
							<div class="form-group">
								<%= f.number_field :collateral, placeholder: "Collateral" %>
							</div>
							<a href="#lending_form" class="toggle_forms_button"><%= button_to "Next"%></a>
						</div>
						<!-- Set Lending Form -->
						<!-- 		  <div class="modal-footer">
							-->
							<div id="lending_form">
								<h4>Set Desired Lending Amount:</h4>
								<p> When you set your loan amount, your friends will be able to automatically borrow from you. This will give you the opportunity to make money through the interest that your friends will pay you in addition to the original amount they borrowed.</p>
								<div class="form-group">
									<%= f.number_field :lending_funds, placeholder: "Lending Funds" %>
								</div>
								<div class="form-group">
									<%= f.submit "Submit", :class => "btn" %>
								</div>
							</div>
						</div>
						<% end %>
					</div>
				</div>
			</div>
			<% end %>
			<!--   		#Add pop-out description of what a collateral is.-->
			
		</body>
	</html>