config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  root 'users#dashboard'    
  get '/static/index' => 'static#index'
  post '/transfers/create' => 'transfers#create'
  resources :accounts, only: [:edit, :update]
  resources :transfers, only: [:edit, :update, :new]

end

app/views/layouts/_header.html.erb
<!-- Header -->
<nav class="navbar navbar-default" role="navigation">
  	<div class="container">
	    <div class="navbar-header">
	      <a href="#" class="navbar-brand">Debit2Credit</a>
	    </div>
  	<%= form_for(resource, as: resource_name, url: user_session_path) do |f| %>
		<div class="LoginHeader">
			<table>
		  <tbody>
		    <tr>
		      <td>
		        <%= f.email_field :email, placeholder: "Email", autofocus: true %>
		      </td>
		      <td>
		        <%= f.password_field :password, placeholder: "Password", autocomplete: "off" %>
		      </td>
		      <td>
		        <%= f.submit "Sign in" %>
		      </td>
		    </tr>
		    <tr>
		      <td>
		        <% if devise_mapping.rememberable? -%>
		            <div>
		              <%= f.check_box :remember_me %> <%= f.label :remember_me %>
		            </div>
		        <% end -%>      
		      </td>
		      <td>
		        <%- if devise_mapping.recoverable? && controller_name != 'passwords' &&   controller_name != 'registrations' %>
		              <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
		          <% end -%>
		      </td>
		    </tr>
		  </tbody>
		  </table>
		  	<% end -%>
	  	</div>
  	</div>
</nav>

app/views/layouts/_howto.html.erb
<div class="howto">
  <div class="row">
        <div class="col-lg-4">
          <img class="howto_images" data-src="holder.js/140x140" alt="140x140" src="/assets/add89.svg">
          <h2>Create User</h2>
          <p>Click on the button above to sign up through Venmo to start setting up your account</p>
<!--           <p><a class="btn btn-default" href="#" role="button">View details »</a></p>
 -->        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="howto_images" data-src="holder.js/140x140" alt="140x140" src="/assets/two205.svg/">
          <h2>Connect with Friends</h2>
          <p>Borrow money from your friends at low rates to help improve your credit standing, or set an amount of money for your friends borrow without risk </p>
          <!-- <p><a class="btn btn-default" href="#" role="button">View details »</a></p> -->
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="howto_images" data-src="holder.js/140x140" alt="140x140" src="/assets/hand132.svg">
          <h2>Ball Out</h2>
          <p>Keep borrowing and watch your credit history grow. If you like lending just sit back, relax, and make dat GUAPPPP. </p>
          <!-- <p><a class="btn btn-default" href="#" role="button">View details »</a></p> -->
        </div><!-- /.col-lg-4 -->
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<link rel="Seed logo icon" href="/assets/favicon.ico" type="image/x-icon" />
  <title>Seed | Social Lending</title>
   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
  <% if flash[:success] %>
    <div class="success">
      <%= flash[:success] %>
    </div>
  <% end %>
  <% if flash[:error] %>
    <div class="error">
      <%= flash[:error] %>
    </div>
  <% end %>
  </div>

  <%= yield %>
</body>
</html>